---
version: "2"
plugins:
  duplication:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true
exclude_patterns:
- "tests/"
