language: php

git:
  depth: 5

env:
  global:
    - COMPOSER_FLAGS=''
    - CC_TEST_REPORTER_ID=a1d38a352ba09d38aa28f376914385fe2434b0e7baee495ab823adb5e670ebb5

matrix:
  include:
    - php: nightly
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
      dist: trusty

install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^nightly ]]; then COMPOSER_FLAGS='--ignore-platform-reqs'; fi
  - travis_retry composer self-update
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phug-dev check --report --coverage-php-version=5.6

notifications:
  slack: phug:nzXFnxhU14RWK2EQSDL0u08z
